version: '2'

services:
  hadoop-master:
    image: halo9pan/hadoop-master
    command: start
    environment:
      - HADOOP_SLAVE_NAMES=hadoop-slave1 hadoop-slave2 hadoop-slave3 hadoop-slave4
    hostname:
      master.hadoop
    ports:
      - "30070:50070"
    expose:
    - "8020"
    volumes:
      - ./logs:/opt/hadoop/logs
    depends_on:
      - hadoop-slave1
      - hadoop-slave2
      - hadoop-slave3
      - hadoop-slave4

  hadoop-slave1:
    image: halo9pan/hadoop-cluster
    hostname:
      slave1.hadoop
    volumes:
      - ./logs:/opt/hadoop/logs

  hadoop-slave2:
    image: halo9pan/hadoop-cluster
    hostname:
      slave2.hadoop
    volumes:
      - ./logs:/opt/hadoop/logs

  hadoop-slave3:
    image: halo9pan/hadoop-cluster
    hostname:
      slave3.hadoop
    volumes:
      - ./logs:/opt/hadoop/logs

  hadoop-slave4:
    image: halo9pan/hadoop-cluster
    hostname:
      slave4.hadoop
    volumes:
      - ./logs:/opt/hadoop/logs

# hadoop-client:
#   image: halo9pan/hadoop-client
#   depends_on:
#     - hadoop-master


networks:
  default:
    external:
      name: Eris

